name: deploy-develop-to-optiplex
on: 
  push:
    branches: 
      - develop
jobs:
  kill-all-node-processes:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - run: kill -9 $(lsof -t -i:3000)
      - run: kill -9 $(lsof -t -i:3001)

  fetch-develop-branch:
    needs: kill-all-node-processes 
    runs-on: self-hosted
    steps:
      - run: cd /home/ocass/optiplex && rm -r -f develop && git clone -b develop https://github.com/revilon99/optiplex develop

  setup-hello-world:
    runs-on: self-hosted
    needs: [kill-all-node-processes, fetch-develop-branch]
    steps:
      - run: cd /home/ocass/optiplex/develop/hello-world && npm install --save

  setup-hello-world-2:
    runs-on: self-hosted
    needs: [kill-all-node-processes, fetch-develop-branch]
    steps:
      - run: cd /home/ocass/optiplex/develop/hello-world-2 && npm install --save
  
  run-all-node-projects:
    runs-on: self-hosted
    needs: [setup-hello-world, setup-hello-world-2]
    steps:
      - run: RUNNER_TRACKING_ID="" && chmod +x /home/ocass/optiplex/develop/run-all-node-projects.sh && /home/ocass/optiplex/develop/run-all-node-projects.sh develop
  
