name: deploy-develop-to-optiplex
on: 
  push:
    branches: 
      - develop
jobs:
  kill-all-node-processes:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - run: kill -9 $(lsof -t -i:3000) || true
      - run: kill -9 $(lsof -t -i:3001) || true

  fetch-develop-branch:
    needs: kill-all-node-processes 
    runs-on: self-hosted
    steps:
      - run: cd /home/ocass/optiplex && rm -r -f develop && git clone -b develop https://github.com/revilon99/optiplex develop
    
  copy-environment:
    needs: fetch-develop-branch
    runs-on: self-hosted
    steps:
      - run: cp /home/ocass/optiplex/config/develop.env /home/ocass/optiplex/develop/.env

  setup-portal:
    runs-on: self-hosted
    needs: copy-environment
    steps:
      - run: cd /home/ocass/optiplex/develop/portal && npm install --save

  setup-auth:
    runs-on: self-hosted
    needs: copy-environment
    steps:
      - run: cd /home/ocass/optiplex/develop/auth && npm install --save
  
  run-all-node-projects:
    runs-on: self-hosted
    needs: [setup-portal, setup-auth]
    steps:
      - run: RUNNER_TRACKING_ID="" && chmod +x /home/ocass/optiplex/develop/run-all-node-projects.sh && /home/ocass/optiplex/develop/run-all-node-projects.sh develop
  
