name: deploy-main-to-optiplex
on: 
  push:
    branches: 
      - main
jobs:
  kill-all-node-processes:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - run: RUNNER_ALLOW_RUNASROOT=1 && killall node

  fetch-main-branch:
    needs: kill-all-node-processes 
    runs-on: self-hosted
    steps:
      - run: cd /home/ocass/optiplex && rm -r -f main && git clone -b main https://github.com/revilon99/optiplex main

  setup-hello-world:
    runs-on: self-hosted
    needs: [kill-all-node-processes, fetch-main-branch]
    steps:
      - run: cd /home/ocass/optiplex/main/hello-world && npm install --save

  setup-hello-world-2:
    runs-on: self-hosted
    needs: [kill-all-node-processes, fetch-main-branch]
    steps:
      - run: cd /home/ocass/optiplex/main/hello-world-2 && npm install --save
  
  run-all-node-projects:
    runs-on: self-hosted
    needs: [setup-hello-world, setup-hello-world-2]
    steps:
      - run: RUNNER_ALLOW_RUNASROOT=1 && RUNNER_TRACKING_ID="" && chmod 775 /home/ocass/optiplex/* && /home/ocass/optiplex/main/run-all-node-projects.sh
  
