name: deploy-main-to-optiplex
on: 
  push:
    branches: 
      - main
jobs:
  kill-all-node-processes:
    runs-on: self-hosted
    steps:
      - run: pkill -f node

  fetch-main-branch:
    needs: kill-all-node-processes 
    runs-on: self-hosted
    steps:
      - run: cd /home/ocass/optiplex && rm -r -f main && git clone -b main https://github.com/revilon99/optiplex main

  run-hello-world:
    runs-on: self-hosted
    needs: [kill-all-node-processes, fetch-main-branch]
    steps:
      - run: cd /home/ocass/optiplex/main/hello-world && npm install --save
      - run: cd /home/ocass/optiplex/main/hello-world && RUNNER_TRACKING_ID="" && (nohup npm run run&)

  run-hello-world-2:
    runs-on: self-hosted
    needs: [kill-all-node-processes, fetch-main-branch]
    steps:
      - run: cd /home/ocass/optiplex/main/hello-world-2 && npm install --save
      - run: cd /home/ocass/optiplex/main/hello-world-2 && RUNNER_TRACKING_ID="" && (nohup npm run run&)