name: deploy-main-to-optiplex
on: 
  push:
    branches: 
      - main
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      # pull main
      - run: cd /home/azureuser/optiplex
      - run: git fetch https://github.com/revilon99/optiplex main

      # run hello-world
      - run: cd hello-world
      - run: npm install --save
      - run: node index.js &
      - run: cd ..
